/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Term_projectUiModule extends AbstractTerm_projectUiModule {

	public Term_projectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
