/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.term_project;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.term_project.Condition#getTeam <em>Team</em>}</li>
 *   <li>{@link org.xtext.example.term_project.Condition#getRobot <em>Robot</em>}</li>
 *   <li>{@link org.xtext.example.term_project.Condition#getGoal <em>Goal</em>}</li>
 *   <li>{@link org.xtext.example.term_project.Condition#getComparator <em>Comparator</em>}</li>
 *   <li>{@link org.xtext.example.term_project.Condition#getDistance <em>Distance</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.term_project.Term_projectPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Team</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Team</em>' attribute.
   * @see #setTeam(String)
   * @see org.xtext.example.term_project.Term_projectPackage#getCondition_Team()
   * @model
   * @generated
   */
  String getTeam();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.Condition#getTeam <em>Team</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Team</em>' attribute.
   * @see #getTeam()
   * @generated
   */
  void setTeam(String value);

  /**
   * Returns the value of the '<em><b>Robot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robot</em>' attribute.
   * @see #setRobot(String)
   * @see org.xtext.example.term_project.Term_projectPackage#getCondition_Robot()
   * @model
   * @generated
   */
  String getRobot();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.Condition#getRobot <em>Robot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robot</em>' attribute.
   * @see #getRobot()
   * @generated
   */
  void setRobot(String value);

  /**
   * Returns the value of the '<em><b>Goal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal</em>' attribute.
   * @see #setGoal(String)
   * @see org.xtext.example.term_project.Term_projectPackage#getCondition_Goal()
   * @model
   * @generated
   */
  String getGoal();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.Condition#getGoal <em>Goal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goal</em>' attribute.
   * @see #getGoal()
   * @generated
   */
  void setGoal(String value);

  /**
   * Returns the value of the '<em><b>Comparator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparator</em>' attribute.
   * @see #setComparator(String)
   * @see org.xtext.example.term_project.Term_projectPackage#getCondition_Comparator()
   * @model
   * @generated
   */
  String getComparator();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.Condition#getComparator <em>Comparator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparator</em>' attribute.
   * @see #getComparator()
   * @generated
   */
  void setComparator(String value);

  /**
   * Returns the value of the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance</em>' attribute.
   * @see #setDistance(int)
   * @see org.xtext.example.term_project.Term_projectPackage#getCondition_Distance()
   * @model
   * @generated
   */
  int getDistance();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.Condition#getDistance <em>Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distance</em>' attribute.
   * @see #getDistance()
   * @generated
   */
  void setDistance(int value);

} // Condition
