/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.term_project;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.term_project.Model#getStatements <em>Statements</em>}</li>
 *   <li>{@link org.xtext.example.term_project.Model#getSimulate <em>Simulate</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.term_project.Term_projectPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.term_project.Team_goal_or_task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.xtext.example.term_project.Term_projectPackage#getModel_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Team_goal_or_task> getStatements();

  /**
   * Returns the value of the '<em><b>Simulate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simulate</em>' containment reference.
   * @see #setSimulate(SimulateStatement)
   * @see org.xtext.example.term_project.Term_projectPackage#getModel_Simulate()
   * @model containment="true"
   * @generated
   */
  SimulateStatement getSimulate();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.Model#getSimulate <em>Simulate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simulate</em>' containment reference.
   * @see #getSimulate()
   * @generated
   */
  void setSimulate(SimulateStatement value);

} // Model
