/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.term_project;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move To Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.term_project.MoveToStatement#getGoal <em>Goal</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.term_project.Term_projectPackage#getMoveToStatement()
 * @model
 * @generated
 */
public interface MoveToStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Goal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal</em>' attribute.
   * @see #setGoal(String)
   * @see org.xtext.example.term_project.Term_projectPackage#getMoveToStatement_Goal()
   * @model
   * @generated
   */
  String getGoal();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.MoveToStatement#getGoal <em>Goal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goal</em>' attribute.
   * @see #getGoal()
   * @generated
   */
  void setGoal(String value);

} // MoveToStatement
