/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.term_project;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simulate Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.term_project.SimulateStatement#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.term_project.SimulateStatement#getRuns <em>Runs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.term_project.Term_projectPackage#getSimulateStatement()
 * @model
 * @generated
 */
public interface SimulateStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see org.xtext.example.term_project.Term_projectPackage#getSimulateStatement_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.SimulateStatement#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

  /**
   * Returns the value of the '<em><b>Runs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.term_project.RunStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runs</em>' containment reference list.
   * @see org.xtext.example.term_project.Term_projectPackage#getSimulateStatement_Runs()
   * @model containment="true"
   * @generated
   */
  EList<RunStatement> getRuns();

} // SimulateStatement
