/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.term_project;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.term_project.TaskDefinition#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.term_project.TaskDefinition#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.term_project.Term_projectPackage#getTaskDefinition()
 * @model
 * @generated
 */
public interface TaskDefinition extends Team_goal_or_task
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see org.xtext.example.term_project.Term_projectPackage#getTaskDefinition_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.term_project.TaskDefinition#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.term_project.TaskStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.xtext.example.term_project.Term_projectPackage#getTaskDefinition_Statements()
   * @model containment="true"
   * @generated
   */
  EList<TaskStatement> getStatements();

} // TaskDefinition
