/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.term_project;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.term_project.Term_projectFactory
 * @model kind="package"
 * @generated
 */
public interface Term_projectPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "term_project";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/Term_project";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "term_project";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Term_projectPackage eINSTANCE = org.xtext.example.term_project.impl.Term_projectPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.ModelImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 0;

  /**
   * The feature id for the '<em><b>Simulate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SIMULATE = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.Team_goal_or_taskImpl <em>Team goal or task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.Team_goal_or_taskImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getTeam_goal_or_task()
   * @generated
   */
  int TEAM_GOAL_OR_TASK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM_GOAL_OR_TASK__NAME = 0;

  /**
   * The number of structural features of the '<em>Team goal or task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM_GOAL_OR_TASK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.TeamDefinitionImpl <em>Team Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.TeamDefinitionImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getTeamDefinition()
   * @generated
   */
  int TEAM_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM_DEFINITION__NAME = TEAM_GOAL_OR_TASK__NAME;

  /**
   * The feature id for the '<em><b>Robots</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM_DEFINITION__ROBOTS = TEAM_GOAL_OR_TASK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Team Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEAM_DEFINITION_FEATURE_COUNT = TEAM_GOAL_OR_TASK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.RobotDefinitionImpl <em>Robot Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.RobotDefinitionImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getRobotDefinition()
   * @generated
   */
  int ROBOT_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_DEFINITION__X = 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_DEFINITION__Y = 2;

  /**
   * The number of structural features of the '<em>Robot Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.GoalDefinitionImpl <em>Goal Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.GoalDefinitionImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getGoalDefinition()
   * @generated
   */
  int GOAL_DEFINITION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_DEFINITION__NAME = TEAM_GOAL_OR_TASK__NAME;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_DEFINITION__X = TEAM_GOAL_OR_TASK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_DEFINITION__Y = TEAM_GOAL_OR_TASK_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Goal Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_DEFINITION_FEATURE_COUNT = TEAM_GOAL_OR_TASK_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.TaskDefinitionImpl <em>Task Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.TaskDefinitionImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getTaskDefinition()
   * @generated
   */
  int TASK_DEFINITION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_DEFINITION__NAME = TEAM_GOAL_OR_TASK__NAME;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_DEFINITION__CONDITION = TEAM_GOAL_OR_TASK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_DEFINITION__STATEMENTS = TEAM_GOAL_OR_TASK_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Task Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_DEFINITION_FEATURE_COUNT = TEAM_GOAL_OR_TASK_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.ConditionImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 6;

  /**
   * The feature id for the '<em><b>Team</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__TEAM = 0;

  /**
   * The feature id for the '<em><b>Robot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__ROBOT = 1;

  /**
   * The feature id for the '<em><b>Goal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__GOAL = 2;

  /**
   * The feature id for the '<em><b>Comparator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__COMPARATOR = 3;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__DISTANCE = 4;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.TaskStatementImpl <em>Task Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.TaskStatementImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getTaskStatement()
   * @generated
   */
  int TASK_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Team</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_STATEMENT__TEAM = 0;

  /**
   * The feature id for the '<em><b>Robot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_STATEMENT__ROBOT = 1;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_STATEMENT__STATEMENT = 2;

  /**
   * The number of structural features of the '<em>Task Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.MoveToStatementImpl <em>Move To Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.MoveToStatementImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getMoveToStatement()
   * @generated
   */
  int MOVE_TO_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Goal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_TO_STATEMENT__GOAL = 0;

  /**
   * The number of structural features of the '<em>Move To Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_TO_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.SimulateStatementImpl <em>Simulate Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.SimulateStatementImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getSimulateStatement()
   * @generated
   */
  int SIMULATE_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMULATE_STATEMENT__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Runs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMULATE_STATEMENT__RUNS = 1;

  /**
   * The number of structural features of the '<em>Simulate Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMULATE_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.term_project.impl.RunStatementImpl <em>Run Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.term_project.impl.RunStatementImpl
   * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getRunStatement()
   * @generated
   */
  int RUN_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN_STATEMENT__FUNCTION = 0;

  /**
   * The number of structural features of the '<em>Run Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN_STATEMENT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.term_project.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.term_project.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.term_project.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.term_project.Model#getSimulate <em>Simulate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Simulate</em>'.
   * @see org.xtext.example.term_project.Model#getSimulate()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Simulate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.Team_goal_or_task <em>Team goal or task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Team goal or task</em>'.
   * @see org.xtext.example.term_project.Team_goal_or_task
   * @generated
   */
  EClass getTeam_goal_or_task();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.Team_goal_or_task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.term_project.Team_goal_or_task#getName()
   * @see #getTeam_goal_or_task()
   * @generated
   */
  EAttribute getTeam_goal_or_task_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.TeamDefinition <em>Team Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Team Definition</em>'.
   * @see org.xtext.example.term_project.TeamDefinition
   * @generated
   */
  EClass getTeamDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.term_project.TeamDefinition#getRobots <em>Robots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Robots</em>'.
   * @see org.xtext.example.term_project.TeamDefinition#getRobots()
   * @see #getTeamDefinition()
   * @generated
   */
  EReference getTeamDefinition_Robots();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.RobotDefinition <em>Robot Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Robot Definition</em>'.
   * @see org.xtext.example.term_project.RobotDefinition
   * @generated
   */
  EClass getRobotDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.RobotDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.term_project.RobotDefinition#getName()
   * @see #getRobotDefinition()
   * @generated
   */
  EAttribute getRobotDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.RobotDefinition#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.example.term_project.RobotDefinition#getX()
   * @see #getRobotDefinition()
   * @generated
   */
  EAttribute getRobotDefinition_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.RobotDefinition#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.example.term_project.RobotDefinition#getY()
   * @see #getRobotDefinition()
   * @generated
   */
  EAttribute getRobotDefinition_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.GoalDefinition <em>Goal Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goal Definition</em>'.
   * @see org.xtext.example.term_project.GoalDefinition
   * @generated
   */
  EClass getGoalDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.GoalDefinition#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.example.term_project.GoalDefinition#getX()
   * @see #getGoalDefinition()
   * @generated
   */
  EAttribute getGoalDefinition_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.GoalDefinition#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.example.term_project.GoalDefinition#getY()
   * @see #getGoalDefinition()
   * @generated
   */
  EAttribute getGoalDefinition_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.TaskDefinition <em>Task Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Definition</em>'.
   * @see org.xtext.example.term_project.TaskDefinition
   * @generated
   */
  EClass getTaskDefinition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.term_project.TaskDefinition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.xtext.example.term_project.TaskDefinition#getCondition()
   * @see #getTaskDefinition()
   * @generated
   */
  EReference getTaskDefinition_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.term_project.TaskDefinition#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.term_project.TaskDefinition#getStatements()
   * @see #getTaskDefinition()
   * @generated
   */
  EReference getTaskDefinition_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.example.term_project.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.Condition#getTeam <em>Team</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Team</em>'.
   * @see org.xtext.example.term_project.Condition#getTeam()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Team();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.Condition#getRobot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Robot</em>'.
   * @see org.xtext.example.term_project.Condition#getRobot()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Robot();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.Condition#getGoal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Goal</em>'.
   * @see org.xtext.example.term_project.Condition#getGoal()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Goal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.Condition#getComparator <em>Comparator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparator</em>'.
   * @see org.xtext.example.term_project.Condition#getComparator()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Comparator();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.Condition#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see org.xtext.example.term_project.Condition#getDistance()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Distance();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.TaskStatement <em>Task Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Statement</em>'.
   * @see org.xtext.example.term_project.TaskStatement
   * @generated
   */
  EClass getTaskStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.TaskStatement#getTeam <em>Team</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Team</em>'.
   * @see org.xtext.example.term_project.TaskStatement#getTeam()
   * @see #getTaskStatement()
   * @generated
   */
  EAttribute getTaskStatement_Team();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.TaskStatement#getRobot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Robot</em>'.
   * @see org.xtext.example.term_project.TaskStatement#getRobot()
   * @see #getTaskStatement()
   * @generated
   */
  EAttribute getTaskStatement_Robot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.term_project.TaskStatement#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Statement</em>'.
   * @see org.xtext.example.term_project.TaskStatement#getStatement()
   * @see #getTaskStatement()
   * @generated
   */
  EReference getTaskStatement_Statement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.MoveToStatement <em>Move To Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move To Statement</em>'.
   * @see org.xtext.example.term_project.MoveToStatement
   * @generated
   */
  EClass getMoveToStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.MoveToStatement#getGoal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Goal</em>'.
   * @see org.xtext.example.term_project.MoveToStatement#getGoal()
   * @see #getMoveToStatement()
   * @generated
   */
  EAttribute getMoveToStatement_Goal();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.SimulateStatement <em>Simulate Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simulate Statement</em>'.
   * @see org.xtext.example.term_project.SimulateStatement
   * @generated
   */
  EClass getSimulateStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.term_project.SimulateStatement#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.xtext.example.term_project.SimulateStatement#getCondition()
   * @see #getSimulateStatement()
   * @generated
   */
  EReference getSimulateStatement_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.term_project.SimulateStatement#getRuns <em>Runs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Runs</em>'.
   * @see org.xtext.example.term_project.SimulateStatement#getRuns()
   * @see #getSimulateStatement()
   * @generated
   */
  EReference getSimulateStatement_Runs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.term_project.RunStatement <em>Run Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Run Statement</em>'.
   * @see org.xtext.example.term_project.RunStatement
   * @generated
   */
  EClass getRunStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.term_project.RunStatement#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Function</em>'.
   * @see org.xtext.example.term_project.RunStatement#getFunction()
   * @see #getRunStatement()
   * @generated
   */
  EAttribute getRunStatement_Function();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Term_projectFactory getTerm_projectFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.ModelImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '<em><b>Simulate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SIMULATE = eINSTANCE.getModel_Simulate();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.Team_goal_or_taskImpl <em>Team goal or task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.Team_goal_or_taskImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getTeam_goal_or_task()
     * @generated
     */
    EClass TEAM_GOAL_OR_TASK = eINSTANCE.getTeam_goal_or_task();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEAM_GOAL_OR_TASK__NAME = eINSTANCE.getTeam_goal_or_task_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.TeamDefinitionImpl <em>Team Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.TeamDefinitionImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getTeamDefinition()
     * @generated
     */
    EClass TEAM_DEFINITION = eINSTANCE.getTeamDefinition();

    /**
     * The meta object literal for the '<em><b>Robots</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEAM_DEFINITION__ROBOTS = eINSTANCE.getTeamDefinition_Robots();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.RobotDefinitionImpl <em>Robot Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.RobotDefinitionImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getRobotDefinition()
     * @generated
     */
    EClass ROBOT_DEFINITION = eINSTANCE.getRobotDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT_DEFINITION__NAME = eINSTANCE.getRobotDefinition_Name();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT_DEFINITION__X = eINSTANCE.getRobotDefinition_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT_DEFINITION__Y = eINSTANCE.getRobotDefinition_Y();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.GoalDefinitionImpl <em>Goal Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.GoalDefinitionImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getGoalDefinition()
     * @generated
     */
    EClass GOAL_DEFINITION = eINSTANCE.getGoalDefinition();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOAL_DEFINITION__X = eINSTANCE.getGoalDefinition_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOAL_DEFINITION__Y = eINSTANCE.getGoalDefinition_Y();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.TaskDefinitionImpl <em>Task Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.TaskDefinitionImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getTaskDefinition()
     * @generated
     */
    EClass TASK_DEFINITION = eINSTANCE.getTaskDefinition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_DEFINITION__CONDITION = eINSTANCE.getTaskDefinition_Condition();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_DEFINITION__STATEMENTS = eINSTANCE.getTaskDefinition_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.ConditionImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Team</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__TEAM = eINSTANCE.getCondition_Team();

    /**
     * The meta object literal for the '<em><b>Robot</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__ROBOT = eINSTANCE.getCondition_Robot();

    /**
     * The meta object literal for the '<em><b>Goal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__GOAL = eINSTANCE.getCondition_Goal();

    /**
     * The meta object literal for the '<em><b>Comparator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__COMPARATOR = eINSTANCE.getCondition_Comparator();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__DISTANCE = eINSTANCE.getCondition_Distance();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.TaskStatementImpl <em>Task Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.TaskStatementImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getTaskStatement()
     * @generated
     */
    EClass TASK_STATEMENT = eINSTANCE.getTaskStatement();

    /**
     * The meta object literal for the '<em><b>Team</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_STATEMENT__TEAM = eINSTANCE.getTaskStatement_Team();

    /**
     * The meta object literal for the '<em><b>Robot</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_STATEMENT__ROBOT = eINSTANCE.getTaskStatement_Robot();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_STATEMENT__STATEMENT = eINSTANCE.getTaskStatement_Statement();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.MoveToStatementImpl <em>Move To Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.MoveToStatementImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getMoveToStatement()
     * @generated
     */
    EClass MOVE_TO_STATEMENT = eINSTANCE.getMoveToStatement();

    /**
     * The meta object literal for the '<em><b>Goal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_TO_STATEMENT__GOAL = eINSTANCE.getMoveToStatement_Goal();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.SimulateStatementImpl <em>Simulate Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.SimulateStatementImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getSimulateStatement()
     * @generated
     */
    EClass SIMULATE_STATEMENT = eINSTANCE.getSimulateStatement();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMULATE_STATEMENT__CONDITION = eINSTANCE.getSimulateStatement_Condition();

    /**
     * The meta object literal for the '<em><b>Runs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMULATE_STATEMENT__RUNS = eINSTANCE.getSimulateStatement_Runs();

    /**
     * The meta object literal for the '{@link org.xtext.example.term_project.impl.RunStatementImpl <em>Run Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.term_project.impl.RunStatementImpl
     * @see org.xtext.example.term_project.impl.Term_projectPackageImpl#getRunStatement()
     * @generated
     */
    EClass RUN_STATEMENT = eINSTANCE.getRunStatement();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RUN_STATEMENT__FUNCTION = eINSTANCE.getRunStatement_Function();

  }

} //Term_projectPackage
