/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractTerm_projectScopeProvider extends XbaseBatchScopeProvider {
}
