/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Term_projectStandaloneSetup extends Term_projectStandaloneSetupGenerated {

	public static void doSetup() {
		new Term_projectStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
