/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.Term_projectRuntimeModule;
import org.xtext.example.Term_projectStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Term_projectIdeSetup extends Term_projectStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Term_projectRuntimeModule(), new Term_projectIdeModule()));
	}
	
}
