/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ide;


/**
 * Use this class to register ide components.
 */
public class Term_projectIdeModule extends AbstractTerm_projectIdeModule {
}
